### ISSUE TITLE
builds x64+x86 when only x86 is requested

### ISSUE THREAD

**Issue by az0** [az0/bbgtkwin#3]
```
%VCPKG_ROOT%\vcpkg.exe install --triplet=x86-windows
  shell: C:\Windows\system[3](https://github.com/bleachbit/pygtkwin/actions/runs/13347473831/job/37279721865#step:6:3)2\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    VCPKG_COMMIT: 058088[5](https://github.com/bleachbit/pygtkwin/actions/runs/13347473831/job/37279721865#step:6:5)32e33f23ac1ad31e32ad0bb1ab8e32195
    VCPKG_DEFAULT_TRIPLET: x8[6](https://github.com/bleachbit/pygtkwin/actions/runs/13347473831/job/37279721865#step:6:6)-windows
    VCPKG_INSTALLED_DIR: D:\a\pygtkwin\pygtkwin/vcpkg/installed
```

then

```
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe
Detecting compiler hash for triplet x86-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x86/cl.exe
The following packages will be built and installed:
  * atk[core,introspection]:x86-windows@2.38.0#9 -- C:\Users\runneradmin\AppData\Local\vcpkg\registries\git-trees\[61](https://github.com/bleachbit/pygtkwin/actions/runs/13347473831/job/37279721865#step:6:62)672c57e8e69aa513f352781240addf75670a4d
  * brotli:x64-windows@1.1.0#1 -- C:\Users\runneradmin\AppData\Local\vcpkg\registries\git-trees\4e5b5ae1ad26c80535c893cc0307121f0398549e
  * brotli:x86-windows@1.1.0#1 -- C:\Users\runneradmin\AppData\Local\vcpkg\registries\git-trees\4e5b5ae1ad26c80535c893cc0307121f0398549e
```

Plus more x64
